### ISSUE TITLE
undefined method `shellescape' for Shellwords:Module

### ISSUE THREAD

**Issue by wrengr** [purcell/darcs-to-git#21]
I get the following error when trying to create a new git clone of a darcs repo:

```
darcs-to-git:169:in `output_of': undefined method `shellescape' for Shellwords:Module (NoMethodError)
    from darcs-to-git:169:in `map'
    from darcs-to-git:169:in `output_of'
    from darcs-to-git:460
```

Setup:
- darcs-to-git 0.2
- darcs 2.5
- git 2.2.1
- ruby 1.8.6 (2009-06-08 patchlevel 369) [universal-darwin9.0]
- OS X 10.5.8

**Comment by tripleee** [comment]
I seem to have Ruby 1.8.7 where Ruby is available at all.  Is there any way to bump down this requirement to be compatible with earlier versions?  I'm looking at Ubuntu 12.04 and Debian Squeeze.

**Comment by purcell** [comment]
@tripleee Okay, so 0c4351b should fix things for you. Please let me know if it doesn't.

**Comment by tripleee** [comment]
Wow, thanks for a really quick fix!

**Comment by purcell** [comment]
Happy to help. :-)
