### ISSUE TITLE
Darcs does not import correctly

### ISSUE THREAD

**Issue by locallycompact** [purcell/darcs-to-git#23]
darcs get http://darcs.net
    git init foo
    cd foo
    darcs-to-git ../darcs.net/
    
Results in:

    Initialising the working area.
    Detected pre-created git repository. If this is not an empty repo, you may encounter problems.
    Repository initialized.
    /home/lc/darcs-bridge/darcs-to-git/darcs-to-git:424:in `darcs_date_to_git_date': Wrong darcs date format: "Sun Sep 21 07:22:44 Pacific Daylight Time 2003" (RuntimeError)
        from /home/lc/darcs-bridge/darcs-to-git/darcs-to-git:298:in `initialize'
        from /home/lc/darcs-bridge/darcs-to-git/darcs-to-git:330:in `new'
        from /home/lc/darcs-bridge/darcs-to-git/darcs-to-git:330:in `block in read_from_repo'
        from /home/lc/darcs-bridge/darcs-to-git/darcs-to-git:329:in `map'
        from /home/lc/darcs-bridge/darcs-to-git/darcs-to-git:329:in `read_from_repo'
        from /home/lc/darcs-bridge/darcs-to-git/darcs-to-git:564:in `<main>'

Any hints?

**Comment by purcell** [comment]
Thanks for reporting that! The code did not handle multi-word time zone names, but that's now fixed.
